### PR TITLE
WIP: MashMap3 merge

### PR DESCRIPTION
**Pull request by bkille**
Updates for mashmap3 source code. Scripts used to calculate Table 1 are in `scripts/MashMap3-evaluation.ipynb`

### CODE REVIEW

**Comment by jianshu93** [comment]
Hello @bkille ,

This is Jianshu, very interested in MashMap, I am wondering whether replacing minimizer with wavefront/wfmash will reduce lowest mapping identity. Mashmap can map down to 78% or so identity, which means, ANI filtering can be down to 78% or so while wavefront will be very slow below 90% identity according the the original paper. Mashmap is also applied for ANI calculation in this paper (https://www.nature.com/articles/s41467-018-07641-9), I am wondering whether Mashmap3 could be also adopted to have an ANI calculator similar to that of Mashmap1.


Thanks,

Jianshu

**Comment by bkille** [comment]
Hi @jianshu93,

Thank you for your interest! This PR only improves on MashMap2, in terms of both speed and ANI prediction, and does not include any wave-front alignment related updates (I'll change the branch-name to reflect that). This PR will update MashMap2 to use a different seeding scheme, to be described in an upcoming preprint.

I'm in the process of changing the CLI interface to match that of MashMap2, and once that's complete the PR should be ready to go.

**Comment by jianshu93** [comment]
Hello @bkille ,

In terms of ANI calculation, e.g., 2 genomes, by how much this mashmap2 improves over mashmap1? I cannot wait to read the preprint, since recently there skani is also using a different seeding and chaining scheme (https://www.biorxiv.org/content/10.1101/2023.01.18.524587.abstract) for very fast ANI calculation/prediciton. Let me know when the preprint is out.

Also, if we can apply wavefront for ANI calculation, e.g. only for larger than 95% or so identities, will it a improve over minimizer (both mashmap1 and 2), just very interested in how it can be or cannot be applied to ANI calculation.


Thanks,

Jianshu

**Comment by bkille** [comment]
@jianshu93 

It depends on the minimum ANI threshold set for the comparison. With higher thresholds i.e. `--pi 95` and higher, there mapping time between the two versions is roughly the same, and MashMap3 requires more overhead to compute the reference index (it allows you to save the index though, so this is a one-time cost). For ANI thresholds below 95%, though, MashMap3 is orders of magnitude faster. I'm moving this to another PR which is more aptly named.

**Pull request closed without merging**
